### ISSUE TITLE
Error: ENOENT: no such file or directory when `/server/build` does not exist

### ISSUE THREAD

**Issue by DomGarguilo** [DomGarguilo/LEDserver#47]
When attempting to start the server for development on a clean install of the project, it will error out when looking for the favicon that does not exist where it is looking for it.

```
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/home/dgarguilo/github/samples/LEDserver/server/build/favicon.ico'
    at Object.statSync (node:fs:1551:3)
    at resolveSync (/home/dgarguilo/github/samples/LEDserver/server/node_modules/serve-favicon/index.js:187:17)
    at favicon (/home/dgarguilo/github/samples/LEDserver/server/node_modules/serve-favicon/index.js:61:12)
    at Object.<anonymous> (/home/dgarguilo/github/samples/LEDserver/server/server.js:106:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/dgarguilo/github/samples/LEDserver/server/build/favicon.ico'
}
```

This happens because during production, there will always be `/build`, the production build created by `npm run build` of the react app, in `/server`. 

To mitigate this error you just need to run `npm run build` within `/client` then copy/move the `build` dir into `/server`. But the project should be resilient to this and at least catch the error and tell the user whats wrong. Better yet, somehow don't require the favicon to be present.

**Comment by DomGarguilo** [comment]
Just points to the fact that the build needs to happen. not an issue to be fixed
